# Generated by Django 3.1.2 on 2020-10-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_no', models.IntegerField(primary_key=True, serialize=False)),
                ('class_ko_name', models.CharField(max_length=50)),
                ('class_en_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'data_classes',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('food_no', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=50, unique=True)),
                ('food_dsc', models.TextField(blank=True, null=True)),
                ('class_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.classes')),
            ],
            options={
                'db_table': 'data_foods',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingre_no', models.AutoField(primary_key=True, serialize=False)),
                ('ingre_name', models.CharField(max_length=50)),
                ('ingre_en_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ingre_allergy', models.BooleanField()),
            ],
            options={
                'db_table': 'data_ingredients',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_no', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'data_tags',
            },
        ),
        migrations.CreateModel(
            name='MapFoodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_no', models.ForeignKey(db_column='food_no', on_delete=django.db.models.deletion.DO_NOTHING, to='foods.foods')),
                ('tag_no', models.ForeignKey(db_column='tag_no', on_delete=django.db.models.deletion.DO_NOTHING, to='foods.tags')),
            ],
            options={
                'db_table': 'map_food_tag',
            },
        ),
        migrations.CreateModel(
            name='MapFoodIngre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_no', models.ForeignKey(db_column='food_no', on_delete=django.db.models.deletion.DO_NOTHING, to='foods.foods')),
                ('ingre_no', models.ForeignKey(db_column='ingre_no', on_delete=django.db.models.deletion.DO_NOTHING, to='foods.ingredients')),
            ],
            options={
                'db_table': 'map_food_ingre',
            },
        ),
    ]
