# Generated by Django 3.1.2 on 2020-10-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergyClasses',
            fields=[
                ('allergy_no', models.IntegerField(primary_key=True, serialize=False)),
                ('allergy_ko_name', models.CharField(max_length=50)),
                ('allergy_en_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'data_allergy_classes',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_no', models.IntegerField(primary_key=True, serialize=False)),
                ('class_ko_name', models.CharField(max_length=50)),
                ('class_en_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'data_classes',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('food_no', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=50)),
                ('food_dsc', models.TextField(null=True)),
                ('class_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.classes')),
            ],
            options={
                'db_table': 'data_foods',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingre_no', models.AutoField(primary_key=True, serialize=False)),
                ('ingre_ko_name', models.CharField(max_length=50)),
                ('ingre_en_name', models.CharField(max_length=50, null=True)),
                ('allergy_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.allergyclasses')),
            ],
            options={
                'db_table': 'data_ingredients',
            },
        ),
        migrations.CreateModel(
            name='MapFoodIngreAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_no', models.ForeignKey(db_column='food_no', on_delete=django.db.models.deletion.CASCADE, to='foods.foods')),
                ('ingre_no', models.ForeignKey(db_column='ingre_no', on_delete=django.db.models.deletion.CASCADE, to='foods.ingredients')),
            ],
            options={
                'db_table': 'map_food_ingre_add',
            },
        ),
        migrations.CreateModel(
            name='MapFoodIngre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_no', models.ForeignKey(db_column='food_no', on_delete=django.db.models.deletion.CASCADE, to='foods.foods')),
                ('ingre_no', models.ForeignKey(db_column='ingre_no', on_delete=django.db.models.deletion.CASCADE, to='foods.ingredients')),
            ],
            options={
                'db_table': 'map_food_ingre',
            },
        ),
    ]
