# Generated by Django 3.1.2 on 2020-10-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_no', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_ko_name', models.CharField(max_length=50)),
                ('tag_en_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'data_tags',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_data', models.DateTimeField(auto_now_add=True)),
                ('rev_star', models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'so so'), ('4', 'good'), ('5', 'very good')], max_length=1)),
                ('rev_spicy', models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'so so'), ('4', 'good'), ('5', 'very good')], max_length=1)),
                ('rev_contents', models.TextField(null=True)),
                ('rev_manual', models.TextField(null=True)),
                ('food_no', models.ForeignKey(db_column='food_no', on_delete=django.db.models.deletion.CASCADE, to='foods.foods')),
                ('user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'data_reviews',
            },
        ),
        migrations.CreateModel(
            name='MapUserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_no', models.ForeignKey(db_column='tag_no', on_delete=django.db.models.deletion.CASCADE, to='reviews.tags')),
                ('user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'map_user_tag',
            },
        ),
        migrations.CreateModel(
            name='MapFoodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_cnt', models.IntegerField()),
                ('food_no', models.ForeignKey(db_column='food_no', on_delete=django.db.models.deletion.CASCADE, to='foods.foods')),
                ('tag_no', models.ForeignKey(db_column='tag_no', on_delete=django.db.models.deletion.CASCADE, to='reviews.tags')),
            ],
            options={
                'db_table': 'map_food_tag',
            },
        ),
    ]
