# Generated by Django 3.1.2 on 2020-10-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_no', models.AutoField(primary_key=True, serialize=False)),
                ('country_ko_name', models.CharField(max_length=50)),
                ('country_en_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'data_countries',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('user_age', models.PositiveSmallIntegerField()),
                ('user_spicy', models.PositiveSmallIntegerField()),
                ('country_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.countries')),
            ],
            options={
                'db_table': 'data_users',
            },
        ),
        migrations.CreateModel(
            name='MapUserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.tags')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'map_user_tag',
            },
        ),
        migrations.CreateModel(
            name='MapUserIngre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingre_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.ingredients')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'map_user_ingre',
            },
        ),
    ]
