# Generated by Django 3.1.2 on 2020-10-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_no', models.AutoField(primary_key=True, serialize=False)),
                ('country_ko_name', models.CharField(max_length=50)),
                ('country_en_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'data_countries',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('user_pw', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('user_age', models.PositiveSmallIntegerField()),
                ('user_spicy', models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'so so'), ('4', 'good'), ('5', 'very good')], max_length=1)),
                ('country_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.countries')),
            ],
            options={
                'db_table': 'data_users',
            },
        ),
        migrations.CreateModel(
            name='MapUserClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_class_no', models.ForeignKey(db_column='food_class_no', on_delete=django.db.models.deletion.CASCADE, to='foods.classes')),
                ('user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'map_user_class',
            },
        ),
        migrations.CreateModel(
            name='MapUserAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_no', models.ForeignKey(db_column='allergy_no', on_delete=django.db.models.deletion.CASCADE, to='foods.allergyclasses')),
                ('user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'map_user_allergy',
            },
        ),
    ]
