# Generated by Django 3.1.1 on 2020-11-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_no', models.AutoField(primary_key=True, serialize=False)),
                ('country_ko_name', models.CharField(max_length=50)),
                ('country_en_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'data_countries',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('user_pw', models.CharField(max_length=128)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('user_birth', models.DateField(blank=True, null=True)),
                ('user_spicy', models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'so so'), ('4', 'good'), ('5', 'very good')], max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('country_no', models.ForeignKey(db_column='country_no', on_delete=django.db.models.deletion.CASCADE, to='user.country')),
            ],
            options={
                'db_table': 'data_users',
            },
        ),
        migrations.CreateModel(
            name='MapUserFoodClass',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('food_class_no', models.ForeignKey(db_column='food_class_no', on_delete=django.db.models.deletion.CASCADE, to='food.foodclass')),
                ('user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'map_user_food_class',
            },
        ),
        migrations.CreateModel(
            name='MapUserEat',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('is_written', models.BooleanField(default=False)),
                ('food_no', models.ForeignKey(db_column='food_no', on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'map_user_eat',
            },
        ),
        migrations.CreateModel(
            name='MapUserAllergy',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('allergy_no', models.ForeignKey(db_column='allergy_no', on_delete=django.db.models.deletion.CASCADE, to='food.allergyclass')),
                ('user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'map_user_allergy',
            },
        ),
    ]
