# Generated by Django 3.1.2 on 2020-11-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_spicy',
            field=models.FloatField(default=0),
        ),
    ]
