# Generated by Django 3.1.1 on 2020-11-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang_no',
            field=models.ForeignKey(db_column='lang_no', default=8, on_delete=django.db.models.deletion.CASCADE, to='user.language'),
        ),
    ]
