# Generated by Django 3.1.2 on 2020-11-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201102_1823'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapfoodtag',
            name='food_no',
            field=models.ForeignKey(db_column='food_no', default=1, on_delete=django.db.models.deletion.CASCADE, to='food.food'),
            preserve_default=False,
        ),
    ]
