# Generated by Django 3.1.2 on 2020-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_star',
            field=models.FloatField(default=0),
        ),
    ]
