# Generated by Django 3.1.1 on 2020-11-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20201122_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_spicy',
            field=models.FloatField(default=0),
        ),
    ]
